### ISSUE TITLE
Main Terminal Window scrolling

### ISSUE THREAD

**Issue by Yo-yo-ooo** [marceldobehere/MaslOS#17]
I found that the window cannot scroll during use

**Comment by Yo-yo-ooo** [comment]
@marceldobehere Is it a bug or other?

**Comment by marceldobehere** [comment]
> I found that the window cannot scroll during use

Could you elaborate? What do you mean during use?

**Comment by Yo-yo-ooo** [comment]
Command line window cannot scroll down when wrapping

**Comment by Yo-yo-ooo** [comment]
![image](https://github.com/marceldobehere/MaslOS/assets/98507772/cca66309-e606-4c51-a652-8d79618f988e)

**Comment by Yo-yo-ooo** [comment]
After reaching a certain number of lines, the window characters will not scroll down

**Comment by Yo-yo-ooo** [comment]
Where is the specific implementation code

**Comment by marceldobehere** [comment]
Would be from here https://github.com/marceldobehere/MaslOS/blob/830e927bcda8070afabf35e63b5a477be47c33a8/kernel/kernel/src/userinput/keyboard.cpp#L239
